### ISSUE TITLE
OMNA common registry missing or corrupt in Dev area

### ISSUE THREAD

**Issue by SvanteAlnas** [OpenMobileAlliance/OMA_LWM2M_Editor#56]
Internal server error, please try later or contact support. OMNA common registry missing or corrupt.

**Comment by seanmcilroy29** [comment]
I've checked the OMNA common file in the DEV area and there was a single dot at the start of the code.
The file has been updated, can you run the test again

**Comment by SvanteAlnas** [comment]
After the update it works again

**Comment by jpradocueva** [comment]
@seanmcilroy29 when was last time the Common file updated? I just would like to know how long the fault was there before we were aware of this change.

**Comment by SvanteAlnas** [comment]
This is in the dev area so its not public, the other issue on invalid versions is public and still not fixed

**Comment by seanmcilroy29** [comment]
The public version should be fixed, could you try again

**Comment by SvanteAlnas** [comment]
I never found this issue in the public area and it still works and now its fixed in the Dev area so i have closed this issue earlier. The public OMNA registry still don't work as reported several days before in the issue:
https://github.com/OpenMobileAlliance/OMA_LWM2M_Editor/issues/54
